### ISSUE TITLE
env: node\r: No such file or directory

### ISSUE THREAD

**Issue by BenGale** [pi0/yarnpm#1]
Getting this error when I try and do anything with npm.

`env: node\r: No such file or directory`

**Comment by pi0** [comment]
@BenGale Thanks for report! But it's odd and i can't reproduce that error. would you please give information about you host operating system and exact error ?

**Comment by BenGale** [comment]
Sure, sorry for the lack of info.

I'm running on OSX El Cap. I'm afraid thats the only error I get when I call npm. I'm using ZSH and NVM if that would cause any issues.

For now, is there anyway to remove it?

**Comment by pi0** [comment]
This problem seems to be related with [This](https://github.com/nwjs/nw-builder/issues/75)
I'm so sorry for inconvenience, this BUG is immediately resolved  on `0.0.4` release.
but for your local fix, please first locate current binary using this: `type npm` then open it with an editor (sudo maybe required) then change first line to something like this :`#node`

**Comment by BenGale** [comment]
So I solved it by uninstalling and reinstalling the node version I'm using, which got me working again.

So now I've tried to install again but when I run the following I get a different error: 

```
[±dev/boxset-details]15:41:16 >> yarnpm yarnpm install 
zsh: /Users/benga/.nvm/versions/node/v6.5.0/bin/yarnpm: bad interpreter: node^M: no such file or directory
```

**Comment by pi0** [comment]
Oh F**\* That Windows! Problem is with line endings... Hold on

**Comment by pi0** [comment]
@BenGale Please Upgrade to `0.0.5`

**Comment by BenGale** [comment]
Another slightly different one:

```
[±dev/boxset-details ●]15:56:36 >> sudo yarnpm yarnpm install                    
/Users/benga/.nvm/versions/node/v6.5.0/lib/node_modules/yarnpm/src/index.js -> /usr/local/bin/npm
fs.js:1054
  return binding.symlink(preprocessSymlinkDestination(target, type, path),
                 ^

Error: EEXIST: file already exists, symlink '/Users/benga/.nvm/versions/node/v6.5.0/lib/node_modules/yarnpm/src/index.js' -> '/usr/local/bin/npm'
    at Error (native)
    at Object.fs.symlinkSync (fs.js:1054:18)
    at installBin (/Users/benga/.nvm/versions/node/v6.5.0/lib/node_modules/yarnpm/src/index.js:94:8)
    at Object.<anonymous> (/Users/benga/.nvm/versions/node/v6.5.0/lib/node_modules/yarnpm/src/index.js:24:13)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
```

Not sure if this is from where I ran the command before?

**Comment by pi0** [comment]
Thanks for helping bugfixes for mac platform :) you can ensure actual link's target with `ls -lah /usr/local/bin/npm`
